name: Build and publish Docker

on:
  pull_request:
    types:
      - closed

jobs:
  build-and-push-docker:
    name: Build and publish Docker
    runs-on: ubuntu-latest

    # Only run if the PR was "merged"
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: latest
